name: Build and Deploy to GitHub Pages

on:
  push:
    # Update branch according from where you will be pushing the code
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        with:
          path: 'woukiebox2_flutter'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release

      # Web deploy now is contained in build/web directory
      - run: |
          cd build
          mkdir web-deploy
          cd web-deploy
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global init.defaultBranch main
          git init
          # the repository to push the deploy into
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/woukie/WoukieBox2-Distributing.git
          git fetch origin gh-pages
          git switch gh-pages
          cp -R ../web/* .
          git status
          git add .
          echo ""
          echo "Committing to gh-pages: ${{ github.event.head_commit.message }}"
          echo ""
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin gh-pages
          
