name: Build and Deploy to GitHub Pages

on:
  push:
    # Update branch according from where you will be pushing the code
    branches: [ main ]

defaults:
  run:
    working-directory: woukiebox2_flutter

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_REPO: https://github.com/Woukie/WoukieBox2-Distributing.git  

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release
      
      - name: Push a file to another repository
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/env/'
          destination_repo: 'woukie/WoukieBox2-Distributing '
          destination_folder: 'app'
          user_email: 'lucaseldon@live.com'
          user_name: 'woukie'
          commit_message: 'Bot push for web app deploy'
